version: '3.8'

services:
  wordpress:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./wordpress:/var/www/html
    environment:
      WORDPRESS_DB_TYPE: "sqlite"
    depends_on:
      - db

  db:
    image: nouchka/sqlite3
    volumes:
      - db_data:/var/www/html/wp-content/database

volumes:
  db_data:

